CREATE COLUMN TABLE audit (
	ID varchar(36) PRIMARY KEY,
	OCCURRED_AT TIMESTAMP NOT NULL,
	ACTION VARCHAR(64) NOT NULL,
	USER VARCHAR(64) NOT NULL,
	MESSAGE VARCHAR(128) NOT NULL,
	CUSTOM VARCHAR(1028) NULL
)